@startuml
'https://plantuml.com/sequence-diagram
!include style.puml
participant ":AddCommand" as AddCommand ADD_COLOR
participant "bookName:Book" as Book BOOK_COLOR
participant ":UI" as UI UI_COLOR
participant ":BookStorage" as BookStorage STORAGE_COLOR
hide footbox
[->AddCommand : handleCommand()
activate AddCommand
AddCommand -> UI: printEmptyArgumentsMessage()
activate UI
UI --> AddCommand
AddCommand -> AddCommand : processAddCommand()
activate AddCommand ADDCOMMAND_COLOR
AddCommand --> AddCommand
deactivate AddCommand

AddCommand -> Book:new Book (newSplitBook:String[])
activate Book
Book --> AddCommand
AddCommand -> BookStorage: writeBookToTxt(bookDataFile: File, listOfBooks: ArrayList<Book>)
activate BookStorage
BookStorage --> AddCommand
[<-- AddCommand
deactivate AddCommand
destroy AddCommand
deactivate Book
destroy Book
deactivate UI
destroy UI
deactivate BookStorage
destroy BookStorage



@enduml