@startuml
!include style.puml

!include <office/Users/user>
!include <office/Concepts/documents>

hide footbox
hide circle
hide members

skinparam class {
    DefaultWidth 200
}

package " " <<rectangle>> {
    Class UI UI_COLOR
    Class Command COMMAND_COLOR
    Class Parser PARSER_COLOR
    Class Storage STORAGE_COLOR
    Class Main MAIN_COLOR
    Class Book BOOK_COLOR
    Class User USER_CLASS_COLOR
    Class UserBook USER_BOOK_COLOR
}

Class "<$user>" as human USER_COLOR
Class "<$documents>" as File FILE_COLOR

UI -[#red]-> Main
Main -[#black]-> UI
Main -[#black]-> Storage
Main -[#black]-> Parser

Parser -[#blue]-> Command
Parser -[#blue]-> Storage
Command -[#orange]-> Book
Command -[#orange]-> User
User -[#salmon]-> UserBook
Storage .[#green].> File
File .[#green].> Storage
human .[#black]> UI



@enduml