@startuml
' Define colors using preprocessor directives
!define UI_COLOR #FFF2CC
!define BORROW_COLOR #D9EAD3
!define USERSTORAGE_COLOR #C9DAF8
!define BOOK_COLOR #EA9999
!define USER_COLOR #D9EAD3

hide footbox

participant ":UI" as Ui UI_COLOR
participant ":BorrowCommand" as borCmd BORROW_COLOR
participant ":UserStorage" as uStorage USERSTORAGE_COLOR
participant ":Book" as book BOOK_COLOR
participant ":User" as user USER_COLOR

[-> borCmd : handleCommand()
activate borCmd

borCmd -> borCmd : setArguments()
activate borCmd #FFBBBB
borCmd --> borCmd
deactivate borCmd

alt if book is found and arguments are valid
    borCmd -> book : isAvailable()
    activate book #ADD8E6
    book --> borCmd
    deactivate book
    destroy book

    alt if book is available and not already borrowed
        borCmd -> book : borrowBook(LocalDate.now(), DEFAULT_BORROW_PERIOD)
        activate book #ADD8E6
        book --> borCmd
        deactivate book

        borCmd -> user : borrowBook(bookIndex, LocalDate.now(), returnDueDate)
        activate user #ADD8E6
        user --> borCmd
        deactivate user
        destroy user

        borCmd -> uStorage : writeUserToTxt(userDataFile, listOfUsers)
        activate uStorage #DarkSalmon
        uStorage --> borCmd
        deactivate uStorage
        destroy uStorage
        
        borCmd -> Ui : printBorrowedMessage(bookName, userName)
        activate Ui #Yellow
        Ui --> borCmd
        deactivate Ui
        destroy Ui
    else if book is already borrowed
        borCmd -> Ui : printUserAlreadyBorrowedBookMessage(userName)
        activate Ui #Yellow
        Ui --> borCmd
        deactivate Ui
        destroy Ui
    else if no copies available
        borCmd -> Ui : printNoAvailableCopiesInInventoryMessage()
        activate Ui #Yellow
        Ui --> borCmd
        deactivate Ui
        destroy Ui
    end

else if book not found or index out of bounds
    borCmd -> Ui : printErrorMessage() ' The error message varies depending on the condition
    activate Ui #Yellow
    Ui --> borCmd
    deactivate Ui
    destroy Ui
end

destroy borCmd

@enduml
