@startuml
!include style.puml

hide circle

skinparam classAttributeIconSize 0

abstract Class Command <<abstract>> {
    + handleCommand()
}

Class FindUserCommand{
}

Class ListUserCommand {
}

Class AddCommand {
}

Class BorrowCommand {
}

Class DeleteCommand {
}

Class EditCommand {
}

Class ExitCommand {

}

Class ExtendCommand {
}

Class FindCommand {
}

Class HelpCommand {

}

Class ListCommand {
}

Class ReturnCommand {
}

Command <|-- AddCommand
Command <|--- BorrowCommand
Command <|-- DeleteCommand
Command <|--- EditCommand
Command <|-- ExitCommand
Command <|--- ExtendCommand
Command <|-- FindCommand
Command <|--- HelpCommand
Command <|-- ListCommand
Command <|--- ReturnCommand
Command <|-- FindUserCommand
Command <|--- ListUserCommand

@enduml