@startuml
' Define colors using preprocessor directives
!define UI_COLOR #FFF2CC
!define DELETE_COLOR #D9EAD3
!define STORAGE_COLOR #C9DAF8
!define BOOK_COLOR #EA9999

hide footbox

' Define participants with colors
participant ":UI" as Ui UI_COLOR
participant ":DeleteCommand" as delCmd DELETE_COLOR
participant ":BookStorage" as bStorage STORAGE_COLOR
participant ":Book" as book BOOK_COLOR

' Sequence of interactions
[-> delCmd : handleCommand()
activate delCmd

delCmd -> delCmd : processDeleteCommand()
activate delCmd DELETE_COLOR
delCmd --> delCmd
deactivate delCmd

delCmd -> bStorage : writeBookToTxt(bookDataFile, listOfBooks)
activate bStorage STORAGE_COLOR
bStorage --> delCmd
deactivate bStorage

delCmd -> delCmd : runDeleteCommand()
activate delCmd DELETE_COLOR
delCmd --> delCmd
deactivate delCmd

delCmd -> book : setNumberInInventory(newNumberInInventory)
activate book BOOK_COLOR
book --> delCmd
deactivate book

delCmd -> book : setNumberTotal(newNumberTotal)
activate book BOOK_COLOR
book --> delCmd
deactivate book

delCmd -> Ui : printDeleteStatement(quantityToDelete, bookName, newNumberInInventory, newNumberTotal)
activate Ui UI_COLOR
Ui --> delCmd
deactivate Ui

[<-- delCmd
deactivate delCmd

@enduml
