@startuml
!include style.puml
hide footbox
participant ":ExitCommand" as Exit EXITCOMMAND_COLOR
participant ":UI" as UI UI_COLOR

[->Exit : handleCommand()
activate Exit

Exit -> UI : exitProgramme()
activate UI

UI --> Exit
deactivate UI
destroy UI
[<-- Exit
deactivate Exit
destroy Exit

@enduml