@startuml
!include style.puml
hide footbox

participant ":ListCommand" as ListCommand LIST_COLOR
participant "listUserCommand :ListUserCommand" as listuser

[->ListCommand : handleCommand()
activate ListCommand

ListCommand -> ListCommand : parseCommand()
activate ListCommand

alt argument is "default"
ListCommand -> ListCommand : runListBlankCommand()
activate ListCommand

ListCommand --> ListCommand
deactivate ListCommand



else argument is "alphabetical"
ListCommand -> ListCommand : runListAlphabeticalCommand()
activate ListCommand
ListCommand --> ListCommand
deactivate ListCommand

else argument is "user"
create listuser
ListCommand -> listuser : new ListUserCommand()
activate listuser
ListCommand -> listuser : handleCommand()
listuser -> listuser : checkUsersAndBooks()
activate listuser
listuser --> listuser
deactivate listuser
listuser --> ListCommand
deactivate listuser






end

ListCommand --> ListCommand
deactivate ListCommand



[<-- ListCommand
destroy listuser
destroy ListCommand
deactivate ListCommand
@enduml