@startuml
!include style.puml

participant ":BookStorage" as BookStorage STORAGE_COLOR
participant "fileReader:BufferedReader" as BufferedReader BUFFERED_READER_COLOR
participant ":FileReader" as FileReader FILE_READER_COLOR

[-> BookStorage : readFileStorage(bookDataFile:File)
activate BookStorage

create BufferedReader
BookStorage -> BufferedReader
activate BufferedReader

create FileReader
BufferedReader -> FileReader
activate FileReader

FileReader --> BufferedReader : new FileReader(bookDataFile:File)
deactivate FileReader

BufferedReader --> BookStorage : new BufferedReader(:FileReader)

BookStorage -> BufferedReader : fileReader.readLine()

BufferedReader --> BookStorage : return currentTextLine:String

loop#physical #technology currentTextLine != null
BookStorage -> BookStorage : addToArrayList(currentTextLine, bookCount, ListOfBooks)
Activate BookStorage

BookStorage --> BookStorage
deactivate BookStorage

BookStorage -> BufferedReader : fileReader.readLine()

BufferedReader --> BookStorage : return currentTextLine:String
end

[<-- BookStorage
deactivate BookStorage
@enduml