@startuml
!include style.puml
hide footbox

participant ":BookStorage" as BookStorage STORAGE_COLOR
participant "fileReader:BufferedReader" as BufferedReader BUFFERED_READER_COLOR
participant ":FileReader" as FileReader FILE_READER_COLOR

[-> BookStorage : readFileStorage(bookDataFile:File)
activate BookStorage

create BufferedReader
BookStorage -> BufferedReader : new BufferedReader(:FileReader)
activate BufferedReader

create FileReader
BufferedReader -> FileReader : new FileReader(bookDataFile:File)
activate FileReader

FileReader --> BufferedReader : return :FileReader
deactivate FileReader
destroy FileReader

BufferedReader --> BookStorage : return fileReader:BufferedReader

BookStorage -> BufferedReader : fileReader.readLine()

BufferedReader --> BookStorage : return currentTextLine:String

loop#physical #technology line != null

BookStorage -> BookStorage : add(book)
Activate BookStorage

BookStorage --> BookStorage
deactivate BookStorage

BookStorage -> BufferedReader : fileReader.readLine()

BufferedReader --> BookStorage : return line:String
deactivate BufferedReader
destroy BufferedReader

end

[<-- BookStorage
deactivate BookStorage
destroy BookStorage

@enduml