@startuml
' Define colors using preprocessor directives
!define UI_COLOR #FFF2CC
!define RETURN_COLOR #D9EAD3
!define USERSTORAGE_COLOR #C9DAF8
!define BOOK_COLOR #EA9999
!define USER_COLOR #D9EAD3

hide footbox

' Define participants with colors
participant ":UI" as Ui UI_COLOR
participant ":ReturnCommand" as retCmd RETURN_COLOR
participant ":UserStorage" as uStorage USERSTORAGE_COLOR
participant ":Book" as book BOOK_COLOR
participant ":User" as user USER_COLOR

' Sequence of interactions
[-> retCmd : handleCommand()
activate retCmd

retCmd -> retCmd : setArguments()
note right
     The setArguments() method
     calls multiple classes such as
     InputValidity or SetUserName.
     For the sake of brevity,
     they are not shown here.
end note
activate retCmd #FFBBBB
retCmd --> retCmd
deactivate retCmd

alt if all arguments are valid
    retCmd -> book : setReturned()
    activate book #ADD8E6
    book --> retCmd
    deactivate book
    destroy book

    retCmd -> user : unborrowBook(bookIndex)
    activate user #ADD8E6
    user --> retCmd
    deactivate user

    ' Check if the user has no more borrowed books and remove them if necessary
    retCmd -> user : getUserBooks()
    activate user #ADD8E6
    user --> retCmd
    deactivate user

    alt if user has no more borrowed books
        retCmd -> retCmd : removeCurrentUserIfNoBookBorrowed()
        activate retCmd #FFBBBB
        retCmd -> uStorage : writeUserToTxt(userDataFile, listOfUsers)
        activate uStorage #DarkSalmon
        uStorage --> retCmd
        deactivate uStorage
        destroy uStorage
        retCmd --> retCmd
        deactivate retCmd

    end

    retCmd -> Ui : printReturnSuccess(bookName)
    activate Ui #Yellow
    Ui --> retCmd
    deactivate Ui
    destroy Ui
else if user not found
    retCmd -> Ui : printNotExistingUserMessage()
    activate Ui #Yellow
    Ui --> retCmd
    deactivate Ui
    destroy Ui
else if book not found
    retCmd -> Ui : printBookNotFoundExceptionMessage()
    activate Ui #Yellow
    Ui --> retCmd
    deactivate Ui
    destroy Ui
else if book not borrowed
    retCmd -> Ui : printBookNotBorrowedByUserMessage(currentUser.getName())
    activate Ui #Yellow
    Ui --> retCmd
    deactivate Ui
    destroy Ui
end

destroy Ui
[<-- retCmd
deactivate retCmd

@enduml

