!define UI_COLOR #red
!define COMMAND_COLOR #yellow
!define PARSER_COLOR #lightblue
!define STORAGE_COLOR #lightgreen
!define MAIN_COLOR #honeydew
!define BOOK_COLOR #orange

!define USER_COLOR #pink
!define FILE_COLOR #limegreen
