@startuml
'https://plantuml.com/sequence-diagram
!include style.puml
hide circle
skinparam classAttributeIconSize 0
Class Ui {
+ greetings()
+ setLineBreak()
+ setSmallerLineBreak()
+ printHelpMessage()
+ printUnknownCommand()
+ printEmptyListMessage()
+ printOutOfBoundsMessage()
+ printBookNotFoundExceptionMessage()
+ printNotNumberMessage()
+ printIncorrectInputFormat()
+ printNoEditChangeException()
+ printEditedBookConfirmation()
+ printDeleteNoCopiesErrorException()
+ printWrongInputFormat()
+ printInvalidTxtLine()
+ printWrongQuantityFormat()
+ printBlankAddQuantity()
+ printNegativeAddQuantityMessage()
+ printMaxDeleteNumberMessage()
+ printNegativeDeleteQuantityMessage()
+ printBlankDeleteQuantity()
+ printMaxNumberMessage()
+ printDeletingTooManyBooksMessage(numberInInventory, quantityToDelete, bookTitle)
+ printEmptyUserListMessage()
+ printDeleteFewerBooksMessage()
+ printDeleteStatement(quantity, bookTitle, numberInventory, numberTotal)
+ incorrectFindArgument()
+ invalidUser(userName)
+ printCommand(user, i)
+ printOverdue()
+ bookIsOverdue()
+ printInvalidTitleMessage()
+ printInvalidBorrowDate(bookTitle)
+ printInvalidReturnDueDate(bookTitle)
+ printInvalidReturnBeforeBorrowDate(bookTitle)
+ printNotExistingUserMessage()
+ printBookNotBorrowedByUserMessage(userName)
+ printNoAvailableCopiesInInventoryMessage()
+ printUserAlreadyBorrowedBookMessage(userName)
+ printInvalidUserTxtLine()
+ printExtensionSuccessMessage(bookName)
+ printModifyBookQuantityMessage(bookName)
+ printInvalidUserMessage()
+ printInvalidBookMessage()
+ printFileNotFoundError()
+ printFileInterruptedError()
+ printDuplicateTitleMessage()
+ printEditSameBookExceptionMessage()
+ printInvalidUsernameMessage()
+ exitProgramme()
+ printUserBooks(user, userCount, listOfUsers)

}
@enduml