@startuml
!include style.puml

hide circle
skinparam classAttributeIconSize 0

Class User {
    - {static} EXTENSION_DAYS: int
    - userName: String
    - listOfBooks: ArrayList<Book>
    - listOfUserBooks: ArrayList<UserBook>
    - userBooksIndex: ArrayList<Integer>
    + getName(): String
    + getUserBooks(): ArrayList<Book>
    + getUserBooksIndex(): ArrayList<Integer>
    + getListOfUserBooks(): ArrayList<UserBook>
    + borrowBook(bookIndex, borrowDate, returnDueDate)
    + unborrowBook(bookIndex): void
    + editBook(oldTitle, newTitle, currentUserBooksList): void
    + extendDueDate(bookIndex): void
    + setListOfBooks(listOfBooks): void
}

Class UserBook {
    - userBookIndex: int
    - userBookTitle: String
    - borrowDate: LocalDate
    - returnDueDate: LocalDate
    + setUserBookTitle(userBookTitle): void
    + setReturnDueDate(returnDate): void
    + getBorrowDate(): LocalDate
    + getReturnDueDate(): LocalDate
    + getUserBookIndex(): int
    + getUserBookTitle(): String
}

User --> "*" UserBook
@enduml