@startuml
!include style.puml
hide footbox

participant ":BookStorage" as BookStorage STORAGE_COLOR
participant "fileWriter:BufferedWriter" as BufferedWriter BUFFERED_WRITER_COLOR
participant ":FileWriter" as FileWriter FILE_WRITER_COLOR

[-> BookStorage : writeBookToTxt(bookDataFile:File, listOfBooks:ArrayList<Book>)
activate BookStorage

create BufferedWriter
BookStorage -> BufferedWriter : new BufferedWriter(:FileWriter)
activate BufferedWriter

create FileWriter
BufferedWriter -> FileWriter : new FileWriter(bookDataFile:File, false:Boolean)
activate FileWriter

FileWriter --> BufferedWriter
deactivate FileWriter
destroy FileWriter

BufferedWriter --> BookStorage
deactivate BufferedWriter

loop#physical #technology i < bookCount

BookStorage -> BookStorage : serializeBook(book:Book)
activate BookStorage

BookStorage --> BookStorage : :String
deactivate BookStorage

BookStorage -> BufferedWriter : write(:String)
activate BufferedWriter

BookStorage <-- BufferedWriter : return
deactivate BufferedWriter
destroy BufferedWriter


end
[<-- BookStorage
deactivate BookStorage
destroy BookStorage

@enduml